export interface User {
  id: string;
  privyId: string;      // Required Privy user ID
  walletAddress: string; // Required wallet address
  emailAddress: string;  // Required email address
  username: string;
  name: string;
  description: string;
  createdAt?: Date;
  updatedAt?: Date;
  farcasterAddress?: string;  // Optional Farcaster connected address
  farcasterFid?: number;      // Optional Farcaster ID
}

// Omit id since it's generated by Supabase
export type CreateUserInput = Omit<User, 'createdAt' | 'updatedAt' | 'id'>;

export interface Publication {
  id: string;
  userId: string;
  address: string;
  standard: string;
  network: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Post {
  id: string;
  publicationId: string;
  publicationAddress: string;
  content_uri: string;
  content: string;  // The actual JSON content from the editor
  title: string | null;  // Title extracted from the content
  tokenId: string;
  transactionHash?: string;
  blockTimestamp?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export type CreatePublicationInput = Omit<Publication, 'id' | 'createdAt' | 'updatedAt'>;
export type CreatePostInput = Omit<Post, 'id' | 'createdAt' | 'updatedAt'>;

export interface Bookmark {
  id: string;
  userId: string;
  publicationAddress: string;
  tokenId: string;
  transactionHash: string;
  createdAt: Date;
  updatedAt: Date;
}

export type CreateBookmarkInput = Omit<Bookmark, 'id' | 'createdAt' | 'updatedAt'>;
